#!/usr/bin/python3
#Author: <put your name here>
#Date:<put todays date here>
#version: 1.0

'''
<insert a description about this program>
'''

import sys

username=sys.argv[1]
print("Hello " + username)